apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  namespace: adhikaria-dev
spec:
  steps:
    - name: build
      image: 'quay.io/buildah/stable:v1.19.6'
      script: |
        buildah bud -f /workspace/Dockerfile -t image-registry.openshift-image-registry.svc:5000/adhikaria-dev/myapp:latest /workspace
        buildah push image-registry.openshift-image-registry.svc:5000/adhikaria-dev/myapp:latest
