apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  namespace: adhikaria-dev
spec:
  steps:
    - name: build
      image: 'quay.io/buildah/stable:v1.19.6'
      script: |
        buildah bud -f /workspace/Dockerfile -t default-route-openshift-image-registry.apps.sandbox-m3.1530.p1.openshiftapps.com/adhikaria-dev/myapp:latest /workspace
        buildah push default-route-openshift-image-registry.apps.sandbox-m3.1530.p1.openshiftapps.com/adhikaria-dev/myapp:latest
