apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  namespace: adhikaria-dev
spec:
  steps:
    - name: trigger-build
      image: 'openshift/origin-cli:latest'
      script: |
        oc start-build myapp -n adhikaria-dev --wait
