apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
  namespace: adhikaria-dev
spec:
  workspaces:
    - name: source
  steps:
    - name: helm-deploy
      image: 'alpine/helm:3.5.4'
      script: |
        helm upgrade --install myapp $(workspaces.source.path)/helm/myapp --namespace adhikaria-dev --set image.tag=latest
