apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rollback-task
  namespace: adhikaria-dev
spec:
  workspaces:
    - name: source
  steps:
    - name: helm-rollback
      image: 'alpine/helm:3.5.4'
      script: |
        cd $(workspaces.source.path)
        helm rollback myapp 1 --namespace adhikaria-dev
