apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-pipeline
  namespace: adhikaria-dev
spec:
  tasks:
    - name: build
      taskRef:
        name: build-task
    - name: deploy
      runAfter:
        - build
      taskRef:
        name: deploy-task
