apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: myapp-pipelinerun
  namespace: adhikaria-dev
spec:
  pipelineRef:
    name: myapp-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: myapp-pvc
  params:
    - name: git-url
      value: "https://github.com/ashutosh1701/myapp.git"
    - name: git-revision
      value: "main"
