apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-pipeline
  namespace: adhikaria-dev
spec:
  workspaces:
    - name: shared-workspace
  resources:
    - name: git-source
      type: git
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      resources:
        - name: git-source
          resource: myapp-git
    - name: build-task
      taskRef:
        name: build-task
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy-task
      taskRef:
        name: deploy-task
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: rollback-task
      taskRef:
        name: rollback-task
      workspaces:
        - name: source
          workspace: shared-workspace
