apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: myapp-git
  namespace: adhikaria-dev
spec:
  type: git
  params:
    - name: url
      value: https://github.com/ashutosh1701/myapp.git
    - name: revision
      value: main
