apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipeline-rolebinding
  namespace: adhikaria-dev
subjects:
- kind: User
  name: adhikaria
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tekton-pipeline-role
  apiGroup: rbac.authorization.k8s.io
