apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: myapp
  namespace: adhikaria-dev
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/ashutosh1701/myapp.git'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'myapp:latest'
  triggers:
    - type: ConfigChange
    - type: ImageChange
  runPolicy: Serial
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
