apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: myapp
  namespace: adhikaria-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/adhikaria-dev/myapp:latest
      importPolicy:
        scheduled: true
    - name: previous
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/adhikaria-dev/myapp:previous
      importPolicy:
        scheduled: true
