apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: myapp
  namespace: adhikaria-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: default-route-openshift-image-registry.apps.sandbox-m3.1530.p1.openshiftapps.com/adhikaria-dev/myapp:latest
      importPolicy:
        scheduled: true
    - name: previous
      from:
        kind: DockerImage
        name: default-route-openshift-image-registry.apps.sandbox-m3.1530.p1.openshiftapps.com/adhikaria-dev/myapp:previous
      importPolicy:
        scheduled: true
